import { useState } from 'react';
import { RefreshCw, Download, CheckCircle2, Circle, ChevronDown, ChevronUp, Loader2, AlertCircle } from 'lucide-react';
import { api } from '../services/api';

export default function SmartChecklist() {
  const [checklist, setChecklist] = useState({
    done: [],
    todo: [],
    suggestions: []
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [showSuggestions, setShowSuggestions] = useState(false);

  const refreshChecklist = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const repoContext = './demo-repo';
      const data = await api.checklist(repoContext);
      setChecklist(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const exportMarkdown = () => {
    const content = `# Boby Testing Checklist

## Done ✓
${checklist.done.map(item => `- [x] ${item}`).join('\n')}

## Todo
${checklist.todo.map(item => `- [ ] ${item}`).join('\n')}

## Suggestions
${checklist.suggestions.map(item => `- ${item}`).join('\n')}

---
Generated by Boby - Developer Assistant
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `boby-checklist-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const hasData = checklist.done.length > 0 || checklist.todo.length > 0;

  return (
    <div className="h-full flex flex-col p-4 bg-slate-900">
      {/* Action buttons */}
      <div className="flex gap-2 mb-4">
        <button
          onClick={refreshChecklist}
          disabled={loading}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 
                     bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 
                     text-white rounded-lg transition-colors duration-200 text-sm font-medium"
        >
          {loading ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <RefreshCw className="w-4 h-4" />
          )}
          <span>{loading ? 'Loading...' : 'Refresh'}</span>
        </button>
        
        {hasData && (
          <button
            onClick={exportMarkdown}
            className="flex items-center justify-center gap-2 px-4 py-2.5 
                       bg-slate-700 hover:bg-slate-600 text-white rounded-lg 
                       transition-colors duration-200 text-sm font-medium"
          >
            <Download className="w-4 h-4" />
            <span>Export</span>
          </button>
        )}
      </div>

      {/* Error message */}
      {error && (
        <div className="mb-4 p-3 bg-red-900/30 border border-red-700 rounded-lg flex items-start gap-2">
          <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
          <p className="text-red-300 text-sm">{error}</p>
        </div>
      )}

      {/* Checklist content */}
      {!hasData && !loading ? (
        <div className="flex-1 flex flex-col items-center justify-center text-center p-4">
          <Circle className="w-12 h-12 text-gray-600 mb-4" />
          <p className="text-gray-400 mb-2">No checklist generated yet</p>
          <p className="text-gray-500 text-sm">Click "Refresh" to generate a testing checklist</p>
        </div>
      ) : (
        <div className="flex-1 overflow-auto space-y-4">
          {/* Done section */}
          {checklist.done.length > 0 && (
            <div className="bg-gray-800 rounded-lg p-4">
              <h3 className="text-green-400 font-semibold mb-3 flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5" />
                Done ({checklist.done.length})
              </h3>
              <ul className="space-y-2">
                {checklist.done.map((item, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm">
                    <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-gray-300">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Todo section */}
          {checklist.todo.length > 0 && (
            <div className="bg-gray-800 rounded-lg p-4">
              <h3 className="text-blue-400 font-semibold mb-3 flex items-center gap-2">
                <Circle className="w-5 h-5" />
                Todo ({checklist.todo.length})
              </h3>
              <ul className="space-y-2">
                {checklist.todo.map((item, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm">
                    <Circle className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
                    <span className="text-gray-300">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Suggestions section (collapsible) */}
          {checklist.suggestions.length > 0 && (
            <div className="bg-gray-800 rounded-lg p-4">
              <button
                onClick={() => setShowSuggestions(!showSuggestions)}
                className="w-full flex items-center justify-between text-yellow-400 font-semibold mb-3 
                           hover:text-yellow-300 transition-colors"
              >
                <span className="flex items-center gap-2">
                  💡 Suggestions ({checklist.suggestions.length})
                </span>
                {showSuggestions ? (
                  <ChevronUp className="w-5 h-5" />
                ) : (
                  <ChevronDown className="w-5 h-5" />
                )}
              </button>
              
              {showSuggestions && (
                <ul className="space-y-2">
                  {checklist.suggestions.map((item, index) => (
                    <li key={index} className="flex items-start gap-2 text-sm">
                      <span className="text-yellow-500 flex-shrink-0">•</span>
                      <span className="text-gray-300">{item}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// Made with Bob
